Vagrant.configure(2) do |config|
  config.ssh.forward_agent    = true
  config.ssh.username         = 'deploy'
  config.vm.hostname          = 'whitelabel.local'
  #config.vm.post_up_message  = 'BerlinOnline DevBox'
  config.vm.box_url           = 'https://projekte.berlinonline.de/box/berlinonline_opensuse-13.2-x86_64_puppet_bo.box'
  config.vm.box               = 'berlinonline_opensuse-13.2-x86_64_puppet_bo'
  config.vm.network :private_network, type: :dhcp
  config.vm.synced_folder "./", "/vagrant/"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path     = "puppets/manifests"
    puppet.manifest_file      = "default.pp"
    puppet.module_path        = "puppets/modules"
    puppet.hiera_config_path  = "puppets/hiera/hiera.yaml"
    puppet.options            = "--debug --parser future --yamldir /vagrant/puppets/hiera"
    puppet.facter = {
      "bo_environment" => "development"
    }

  end

end
