Vagrant.configure(2) do |config|
  config.ssh.username                   = 'deploy'
  config.ssh.forward_agent              = true

  config.vm.hostname                    = 'hb-showcase.local'

  config.vm.box                         = 'berlinonline/opensuse-13_2'
  config.vm.boot_timeout                = 300

  config.vm.network :private_network, type: :dhcp
  config.vm.synced_folder "puppets/hiera/", "/vagrant/hiera"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "showcase-cms"
    vb.memory = "1024"
    vb.cpus   = 2
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path    = "puppets/manifests"
    puppet.manifest_file     = "default.pp"
    puppet.module_path       = "puppets/modules"
    puppet.hiera_config_path = "puppets/hiera/hiera.yaml"
    puppet.options           = "--parser future --yamldir /vagrant/puppets/hiera"
    puppet.facter            = {
      "bo_environment" => "development"
    }

  end

end
