# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #########################
  # setting for all boxes #
  #########################
  config.vm.box = "shrink0r/ubuntu-trusty-server-x64"     # vagrantcloud box
  config.vm.box_url = "shrink0r/ubuntu-trusty-server-x64" # vagrantcloud box
  config.vm.network :private_network, type: :dhcp
  config.ssh.forward_agent = true
  config.vbguest.auto_update = false
  # shell provisioner running only once every 48 hours
  config.vm.provision :shell, :inline =>'[ "$(find /home/vagrant/ -maxdepth 1 -name apt_updated -mtime -48)" == "" ] && apt-get update --fix-missing && touch /home/vagrant/apt_updated; echo ""'

  ###############
  # backend box #
  ###############
  config.vm.define :cms do |cms|
    cms.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--name", "hb-showcase-cms-trusty-x64"] # name for VirtualBox GUI
      vb.customize ["modifyvm", :id, "--memory", 1024]
    end
    cms.vm.hostname = "hb-showcase-cms.local"
    cms.vm.provision :puppet do |puppet|
      puppet.manifests_path = "./"
      puppet.manifest_file = "manifest-cms.pp"
      puppet.module_path = [ "../../modules", "../../../puppets/modules" ]
      puppet.options = "--verbose --debug"
    end
  end

end
